In [19]:
import pandas as pd
import numpy as np
import seaborn as sn
import pandas_profiling
from  sklearn.preprocessing import  LabelEncoder
import matplotlib.pyplot as plt

In [20]:
athletes=pd.read_csv("tokyo/athletes.csv")
medal=pd.read_csv("tokyo/medals.csv")

In [21]:
print(athletes.shape)
print(medal.shape)

(4527, 9)
(2142, 7)

In [24]:
athletes=athletes.drop(["Date of Birth","Age"],axis=1)

In [25]:
athletes.head()

,Name,Country,CountryCode,Sport,Sport-code,Gender,Age.1
0,AAJIM Munkhbat,Mongolia,MGL,Judo,JUD,Male,32
1,ABARZA Alberto,Chile,CHI,Swimming,SWM,Male,36
2,ABASLI Namig,Azerbaijan,AZE,Judo,JUD,Male,23
3,ABASSI Mostefa,Algeria,ALG,Wheelchair Basketball,WBK,Male,43
4,ABBAD Abderraouf,Algeria,ALG,Wheelchair Basketball,WBK,Male,34

In [7]:
medal.head()

,Country,CountryCode,Name,Sport,Sport-short,Event,Medal
0,Czech Republic,CZE,DRAHONINSKY David,Archery,ARC,Men's Individual - W1,Gold Medal
1,People's Republic of China,CHN,HE Zihao,Archery,ARC,Men's Individual Compound - Open,Gold Medal
2,United States of America,USA,MATHER Kevin,Archery,ARC,Men's Individual Recurve - Open,Gold Medal
3,People's Republic of China,CHN,CHEN Minyi,Archery,ARC,Women's Individual - W1,Gold Medal
4,Great Britain,GBR,PATERSON PINE Phoebe,Archery,ARC,Women's Individual Compound - Open,Gold Medal

In [11]:
data=pd.DataFrame()

In [41]:
data['Name']=athletes['Name']
allnames=list(data['Name'])
data['Sex']=athletes['Gender']
data['Age']=athletes['Age.1']
data['Team']=athletes['Country']
data['Season']="Summer"
data['Medal']=0

In [38]:
data.head()

               Name   Sex  Age        Team  Season  Medal
0    AAJIM Munkhbat  Male   32    Mongolia  Summer      0
1    ABARZA Alberto  Male   36       Chile  Summer      0
2      ABASLI Namig  Male   23  Azerbaijan  Summer      0
3    ABASSI Mostefa  Male   43     Algeria  Summer      0
4  ABBAD Abderraouf  Male   34     Algeria  Summer      0

In [42]:
names=list(medal['Name'])
medals=list(medal['Medal'])
l=[]

In [ ]:
names.index("ABASSI Mostefa")

In [52]:

print(medals[1705])

Bronze Medal

In [45]:
for i in allnames:
    if (i in names):
        index=names.index(i)
        value=medals[index]
        l.append(value)
    else:
        l.append(np.NaN)

In [46]:
l

[nan,
 nan,
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 'Gold Medal',
 'Silver Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 'Bronze Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 'Bronze Medal',
 'Bronze Medal',
 'Silver Medal',
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 'Gold Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 'Gold Medal',
 nan,
 'Silver Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 'Bronze Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Bronze Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 'Gold Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 'Gold Medal',
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 'Bronze Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 'Gold Medal',
 'Gold Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Gold Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 'Silver Medal',
 'Silver Medal',
 nan,
 'Silver Medal',
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Silver Medal',
 'Silver Medal',
 'Bronze Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 'Gold Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 'Gold Medal',
 nan,
 'Bronze Medal',
 'Gold Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Silver Medal',
 'Gold Medal',
 nan,
 'Gold Medal',
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 'Silver Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 'Bronze Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 'Silver Medal',
 nan,
 'Silver Medal',
 nan,
 'Bronze Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Gold Medal',
 'Gold Medal',
 nan,
 'Bronze Medal',
 nan,
 'Silver Medal',
 'Gold Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 'Silver Medal',
 'Bronze Medal',
 nan,
 'Silver Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 'Gold Medal',
 'Silver Medal',
 nan,
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Gold Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 'Gold Medal',
 'Silver Medal',
 nan,
 nan,
 'Silver Medal',
 'Gold Medal',
 'Silver Medal',
 'Silver Medal',
 'Gold Medal',
 'Silver Medal',
 nan,
 'Gold Medal',
 'Gold Medal',
 'Silver Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 'Bronze Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 'Gold Medal',
 'Gold Medal',
 'Silver Medal',
 'Bronze Medal',
 nan,
 nan,
 'Silver Medal',
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 'Gold Medal',
 nan,
 'Silver Medal',
 'Silver Medal',
 'Silver Medal',
 'Gold Medal',
 nan,
 'Silver Medal',
 nan,
 'Gold Medal',
 'Silver Medal',
 'Gold Medal',
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Silver Medal',
 'Silver Medal',
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 'Gold Medal',
 'Gold Medal',
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Gold Medal',
 'Gold Medal',
 nan,
 'Silver Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Silver Medal',
 'Silver Medal',
 'Gold Medal',
 'Gold Medal',
 'Bronze Medal',
 'Gold Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 'Silver Medal',
 'Gold Medal',
 nan,
 'Gold Medal',
 'Silver Medal',
 nan,
 nan,
 'Bronze Medal',
 'Silver Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Bronze Medal',
 'Bronze Medal',
 'Silver Medal',
 'Silver Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Bronze Medal',
 'Silver Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Silver Medal',
 nan,
 'Bronze Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 'Bronze Medal',
 'Gold Medal',
 'Silver Medal',
 nan,
 'Bronze Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 nan,
 'Gold Medal',
 'Gold Medal',
 nan,
 nan,
 'Bronze Medal',
 nan,
 'Bronze Medal',
 nan,
 'Gold Medal',
 'Bronze Medal',
 nan,
 nan,
 'Gold Medal',
 nan,
 'Silver Medal',
 'Bronze Medal',
 'Silver Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 nan,
 nan,
 'Bronze Medal',
 'Silver Medal',
 'Gold Medal',
 'Gold Medal',
 'Silver Medal',
 nan,
 'Silver Medal',
 'Bronze Medal',
 nan,
 nan,
 'Gold Medal',
 'Silver Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 'Silver Medal',
 nan,
 'Gold Medal',
 nan,
 nan,
 'Silver Medal',
 'Gold Medal',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Bronze Medal',
 nan,
 nan,
 nan,
 'Silver Medal',
 'Silver Medal',
 nan,
 'Bronze Medal',
 'Bronze Medal',
 nan,
 ...]

In [32]:
data.head()

               Name   Sex  Age        Team  Season  Medal
0    AAJIM Munkhbat  Male   32    Mongolia  Summer      0
1    ABARZA Alberto  Male   36       Chile  Summer      0
2      ABASLI Namig  Male   23  Azerbaijan  Summer      0
3    ABASSI Mostefa  Male   43     Algeria  Summer      0
4  ABBAD Abderraouf  Male   34     Algeria  Summer      0