In [3]:
import pandas as pd
import numpy as np
import seaborn as sn
import pandas_profiling
from  sklearn.preprocessing import  LabelEncoder
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv("./archive/main.csv")
data

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [5]:
data=data.drop(['ID','Height','Weight','NOC','City','Event'],axis=1)

In [6]:
data['Medal'].fillna(value=0, inplace=True)
data['Medal']=data['Medal'].replace('Gold',3)
data['Medal']=data['Medal'].replace('Silver',2)
data['Medal']=data['Medal'].replace('Bronze',1)

In [7]:
data.isnull().sum()

Name         0
Sex          0
Age       9474
Team         0
Games        0
Year         0
Season       0
Sport        0
Medal        0
dtype: int64

In [8]:
# run the profile report
#profile = data.profile_report(title='Pandas Profiling Report')
   
# save the report as html file
#profile.to_file(output_file="pandas_profiling1.html")

In [9]:
dataplot = sn.heatmap(data.corr(), cmap="OrRd")
plt.show()

<ipython-input-9-091a00d7d2aa>:2: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

We are counting the winter season data of the years which coincided with the summer season data.

In [10]:
data

,Name,Sex,Age,Team,Games,Year,Season,Sport,Medal
0,A Dijiang,M,24.0,China,1992 Summer,1992,Summer,Basketball,0
1,A Lamusi,M,23.0,China,2012 Summer,2012,Summer,Judo,0
2,Gunnar Nielsen Aaby,M,24.0,Denmark,1920 Summer,1920,Summer,Football,0
3,Edgar Lindenau Aabye,M,34.0,Denmark/Sweden,1900 Summer,1900,Summer,Tug-Of-War,3
4,Christine Jacoba Aaftink,F,21.0,Netherlands,1988 Winter,1988,Winter,Speed Skating,0
...,...,...,...,...,...,...,...,...,...
271111,Andrzej ya,M,29.0,Poland-1,1976 Winter,1976,Winter,Luge,0
271112,Piotr ya,M,27.0,Poland,2014 Winter,2014,Winter,Ski Jumping,0
271113,Piotr ya,M,27.0,Poland,2014 Winter,2014,Winter,Ski Jumping,0
271114,Tomasz Ireneusz ya,M,30.0,Poland,1998 Winter,1998,Winter,Bobsleigh,0
271115,Tomasz Ireneusz ya,M,34.0,Poland,2002 Winter,2002,Winter,Bobsleigh,0

In [11]:
tokyo=pd.read_csv("2020_tokyo_olympics.csv")
tokyo.drop("Unnamed: 0",axis=1)

FileNotFoundError: [Errno 2] No such file or directory: '2020_tokyo_olympics.csv'

In [12]:
final= pd.concat([data, tokyo], axis=0)
final=final.drop("Unnamed: 0",axis=1)
final

NameError: name 'tokyo' is not defined

In [13]:
final

NameError: name 'final' is not defined

In [13]:
final.isnull().sum()

Name         0
Sex          0
Age       9474
Team         0
Games        0
Year         0
Season       0
Sport        0
Medal        0
dtype: int64

In [14]:
final.head(100)

,Name,Sex,Age,Team,Games,Year,Season,Sport,Medal
0,A Dijiang,M,24.0,China,1992 Summer,1992,Summer,Basketball,0
1,A Lamusi,M,23.0,China,2012 Summer,2012,Summer,Judo,0
2,Gunnar Nielsen Aaby,M,24.0,Denmark,1920 Summer,1920,Summer,Football,0
3,Edgar Lindenau Aabye,M,34.0,Denmark/Sweden,1900 Summer,1900,Summer,Tug-Of-War,3
4,Christine Jacoba Aaftink,F,21.0,Netherlands,1988 Winter,1988,Winter,Speed Skating,0
...,...,...,...,...,...,...,...,...,...
95,Olav Augunson Aarnes,M,23.0,Norway,1912 Summer,1912,Summer,Athletics,0
96,Mika Lauri Aarnikka,M,24.0,Finland,1992 Summer,1992,Summer,Sailing,0
97,Mika Lauri Aarnikka,M,28.0,Finland,1996 Summer,1996,Summer,Sailing,0
98,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,France,2012 Summer,2012,Summer,Athletics,0
99,Dagfinn Sverre Aarskog,M,24.0,Norway,1998 Winter,1998,Winter,Bobsleigh,0

In [15]:
final.to_csv("Olympics_Dataset_(with_2020).csv")